discuss/lib/discuss_web/router.ex
defmodule DiscussWeb.Router do
  use DiscussWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Discuss.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", DiscussWeb do
    pipe_through :browser # Use the default browser stack

    resources "/", TopicController
  end

  scope "/auth", Discuss do
    pipe_through :browser

    get "/signout", AuthController, :signout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", DiscussWeb do
  #   pipe_through :api
  # end
end

discuss/lib/discuss/application.ex
defmodule Discuss.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Discuss.Repo, []),
      # Start the endpoint when the application starts
      supervisor(DiscussWeb.Endpoint, []),
      # Start your own worker by calling: Discuss.Worker.start_link(arg1, arg2, arg3)
      # worker(Discuss.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Discuss.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    DiscussWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

discuss/lib/discuss/comment.ex
defmodule Discuss.Comment do
  
  use Ecto.Schema
  import Ecto.Changeset
  
  alias Discuss.Comment


  @derive {Poison.Encoder, only: [:content, :user]}

  schema "comments" do
    field :content, :string

    belongs_to :user, Discuss.User
    belongs_to :topic, Discuss.Topic

    timestamps()
  end

  @doc false
  def changeset(%Comment{} = comment, attrs \\ %{}) do
    comment
    |> cast(attrs, [:content])
    |> validate_required([:content])
  end
end

discuss/lib/discuss/repo.ex
defmodule Discuss.Repo do
  use Ecto.Repo, otp_app: :discuss

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

discuss/lib/discuss/topic.ex
defmodule Discuss.Topic do
  use Ecto.Schema
  import Ecto.Changeset
  alias Discuss.Topic


  schema "topics" do
    field :title, :string

    belongs_to :user, Discuss.User
    has_many :comments, Discuss.Comment
  end

  @doc false
  def changeset(%Topic{} = topic, attrs \\ %{}) do
    topic
    |> cast(attrs, [:title])
    |> validate_required([:title])
  end
end

discuss/lib/discuss/user.ex
defmodule Discuss.User do
  
  use Ecto.Schema
  import Ecto.Changeset
  alias Discuss.Topic

  @derive {Poison.Encoder, only: [:id, :email]}

  schema "users" do
    field :email, :string
    field :provider, :string
    field :token, :string

    has_many :topics, Discuss.Topic
    has_many :comments, Discuss.Comment
    
    timestamps()
  end

  def changeset(struct, params \\ %{}) do 
    struct
    |> cast(params, [:email, :provider, :token])
    |> validate_required([:email, :provider, :token])
  end

end

discuss/lib/discuss_web/controllers/auth_controller.ex
defmodule Discuss.AuthController do
  use DiscussWeb, :controller
  plug Ueberauth

  alias Discuss.User
  alias Discuss.Repo

  def callback(%{assigns: %{ueberauth_auth: auth}} = conn, params) do

    user_params = %{token: auth.credentials.token, email: auth.info.email, provider: "github" }
    changeset = User.changeset(%User{}, user_params)

    signin(conn, changeset)
  end


  def signout(conn, _params) do
    
    # # I MADE THIS ONE AND I PREFER THIS ONE THAN THE OTHER ONE BELOW
    # conn
    # |> delete_session(:user_id)
    # |> put_flash(:info, "Sign out")
    # |> redirect(to: topic_path(conn, :index))

    conn
    |> configure_session(drop: true)
    |> put_flash(:info, "Sign out")
    |> redirect(to: topic_path(conn, :index))
  end

  defp signin(conn, changeset) do
    case insert_or_update_user(changeset) do
      {:ok, user} -> 
        conn
        |> put_flash(:info, "Welcome back!")
        |> put_session(:user_id, user.id)
        |> redirect(to: topic_path(conn, :index))
      {:error, _reason} ->
        conn
        |> put_flash(:info, "An error occured.")
        |> redirect(to: topic_path(conn, :index))
    end
  end

  defp insert_or_update_user(changeset) do
    case Repo.get_by(User, email: changeset.changes.email) do
      nil -> 
        Repo.insert(changeset)
      user -> 
        {:ok , user}
    end
  end
end

discuss/lib/discuss_web/controllers/topic_controller.ex
defmodule DiscussWeb.TopicController do
  use DiscussWeb, :controller
 
  import Ecto

  alias Discuss.Repo 
  alias Discuss.Topic

  plug Discuss.Plugs.RequireAuth when action in [:new, :create, :edit, :update, :delete]
  plug :check_topic_owner when action in [:update, :edit, :delete]

  def index(conn, _) do
  	topics = Repo.all(Topic)
  	render conn, "index.html", topics: topics
  end

  def show(conn, %{"id" => topic_id}) do
    topic = Repo.get!(Topic, topic_id)

    render conn, "show.html", topic: topic
  end

  # ----------------------
  
  def new(conn, _) do
  	changeset = Topic.changeset(%Topic{}, %{})

  	render conn, "new.html", changeset: changeset
  end

  def create(conn, %{"topic" => topic}) do
    changeset = conn.assigns[:user]
    |> Ecto.build_assoc(:topics)
    |> Topic.changeset(topic)

  	case Repo.insert(changeset) do 
  		{:ok, _post } ->
  			conn
  			|> put_flash(:info, "Topic Created")
  			|> redirect(to: topic_path(conn, :index))
  			render conn, "index.html"
  		{:error, changeset } ->
  			render conn, "new.html", changeset: changeset
  	end
  end

  # ----------------------

  def edit(conn, %{"id" => topic_id}) do
    topic = Repo.get(Topic, topic_id)
    changeset = Topic.changeset(topic)
    render conn, "edit.html", topic: topic, changeset: changeset
  end

  def update(conn, %{"id" => topic_id, "topic" => topic}) do
    old_topic = Repo.get(Topic, topic_id)
    changeset = Topic.changeset(old_topic, topic)

    case Repo.update(changeset) do
      {:ok, _post} ->
          conn
          |> put_flash(:info, "Topic Updated")
          |> redirect(to: topic_path(conn, :index))
      {:error, changeset } -> render conn, "edit.html", changeset: changeset, topic: old_topic
    end
  end

  # ----------------------

  def delete(conn, %{"id" => topic_id}) do
    Repo.get!(Topic, topic_id) |> Repo.delete!

    conn
    |> put_flash(:info, "Topic Deleted")
    |> redirect(to: topic_path(conn, :index))
  end

  defp check_topic_owner(conn, _) do
    %{params: %{"id" => topic_id}} = conn

    if Repo.get!(Topic, topic_id).user_id == conn.assigns.user.id do
      conn
    else
      conn 
      |> put_flash(:error, "You cannot edit that")
      |> redirect(to: topic_path(conn, :index))
      |> halt()
    end

  end

end

discuss/lib/discuss_web/views/error_view.ex
defmodule DiscussWeb.ErrorView do
  use DiscussWeb, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

discuss/lib/discuss_web/views/layout_view.ex
defmodule DiscussWeb.LayoutView do
  use DiscussWeb, :view
end

discuss/lib/discuss_web/views/page_view.ex
defmodule DiscussWeb.PageView do
  use DiscussWeb, :view
end

discuss/lib/discuss_web/views/topic_view.ex
defmodule DiscussWeb.TopicView do
  use DiscussWeb, :view
end

discuss/lib/discuss_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Discuss!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <%= if @conn.assigns.user do %>
      <script>window.userToken = "<%= Phoenix.Token.sign(DiscussWeb.Endpoint, "key", @conn.assigns.user.id) %>";</script>
    <% end %>

  </head>

  <body>

      <nav class='light-blue'>
        <div class='nav-wrapper container'>
          <a href="/" class='brand-logo'>
            Discussions
          </a>
          <ul class="right">
            <%= if @conn.assigns[:user] do %>
              <li><%= link "Log out", to: auth_path(@conn, :signout) %></li>
            <% else %>
              <li>
                <%= link "Sign in with Github", to: auth_path(@conn, :request, "github") %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>



    <div class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>


      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>


    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

discuss/lib/discuss_web/templates/topic/edit.html.eex
<%= form_for @changeset, topic_path(@conn, :update, @topic.id), fn f -> %>

	<div class="form-group">
		<%= text_input f, :title, placeholder: "Title", class: "form-control" %>
		<%= error_tag f, :title %>
	</div>

	<%= submit "Save Topic", class: "btn btn-primary" %>
<% end %>

discuss/lib/discuss_web/templates/topic/index.html.eex
<h5>Topics</h5> 

<ul class="collection">
  <%= for topic <- @topics do %>
    <li class='collection-item'>
      <%= link topic.title, to: topic_path(@conn, :show, topic.id) %>


      <%= if @conn.assigns.user && @conn.assigns.user.id == topic.user_id do %>
        <div class="right">
          <%= link "Edit", to: topic_path(@conn, :edit, topic) %>
          <%= link "Delete", to: topic_path(@conn, :delete, topic), method: :delete %>
        </div>
      <% end %>

    </li>


  <% end %>
</ul>


<div class="fixed-action-btn">
<%= link to: topic_path(@conn, :new), class: "btn-floating btn-large waves-effect waves-light red" do %>
  <i class="material-icons">add</i>
<% end %>
</div>

discuss/lib/discuss_web/templates/topic/new.html.eex
<%= form_for @changeset, topic_path(@conn, :create), fn f -> %>

	<div class="form-group">
		<%= text_input f, :title, placeholder: "Title", class: "form-control" %>
		<%= error_tag f, :title %>
	</div>

	<%= submit "Save Topic", class: "btn btn-primary" %>
<% end %>

discuss/lib/discuss_web/templates/topic/show.html.eex
<h5><%= @topic.title %></h5>

<div class="input-field">
	<textarea class="materialize-textarea"></textarea>
	<button class="btn">Add comment</button>
</div>

<ul class="collection"></ul>


<script>
	document.addEventListener("DOMContentLoaded", function() {
		window.createSocket(<%= @topic.id %>)
	})
</script>